spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
server:
  servlet:
    context-path: /dev

---
spring:
  config:
    activate:
      on-profile: mock
server:
  servlet:
    context-path: /mock

---
logging:
  file.name: logs/app.log
  pattern:
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org.example.exchangerate: debug
    org.springframework: error
    org.hibernate: error

